name: Gulp build and commit updated stylesheets

on: [push]

jobs:
  gulp-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Compile with Gulp
      uses: elstudio/actions-js-build/build@v2

    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUSH_BRANCH: 'Testing'
